FROM registry.access.redhat.com/ubi8/ubi:latest


RUN yum update -y && \
    yum install -y logrotate && \
    yum clean all


RUN mkdir -p /etc/logrotate.d \
    && mkdir -p /var/lib/logrotate \
    && chmod 755 /var/lib/logrotate \
    && touch /var/lib/logrotate/logrotate.status \
    && chmod 755 /var/lib/logrotate/logrotate.status \
    && touch /etc/logrotate.d/logrotate.conf


RUN echo "/opt/apache/tomcat/base/logs/catalina.out {" > /etc/logrotate.d/custom-logrotate && \
    echo "    copytruncate" >> /etc/logrotate.d/custom-logrotate && \
    echo "    size 1M" >> /etc/logrotate.d/custom-logrotate && \
    echo "    missingok" >> /etc/logrotate.d/custom-logrotate && \
    echo "    rotate 5" >> /etc/logrotate.d/custom-logrotate && \
    echo "    compress" >> /etc/logrotate.d/custom-logrotate && \
    echo "    maxage 7" >> /etc/logrotate.d/custom-logrotate && \
    echo "    notifempty" >> /etc/logrotate.d/custom-logrotate && \
    echo "    prerotate" >> /etc/logrotate.d/custom-logrotate && \
    echo "         find /var/log/tomcat/ -name \"localhost_access_log.*.txt\" -size 0 -delete" >> /etc/logrotate.d/custom-logrotate && \
    echo "    endscript" >> /etc/logrotate.d/custom-logrotate && \
    echo "    postrotate" >> /etc/logrotate.d/custom-logrotate && \
    echo "         find /var/log/tomcat/ -name \"localhost_access_log.*.txt.*\" -size 0 -delete" >> /etc/logrotate.d/custom-logrotate && \
    echo "    endscript" >> /etc/logrotate.d/custom-logrotate && \
    echo "    create 0755 root root" >> /etc/logrotate.d/custom-logrotate && \
echo "}" >> /etc/logrotate.d/custom-logrotate

CMD ["tail", "-f", "/dev/null"]
